SET default_storage_engine=InnoDB;
-- MySQL Script generated by MySQL Workbench
-- Sun Jan 15 10:52:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema minder
-- ----------------------------------------somethinggreen-------------

-- -----------------------------------------------------
-- Schema minder
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `minder` DEFAULT CHARACTER SET UTF8 ;
-- USE `minder` ;

-- -----------------------------------------------------
-- Table `minder`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minder`.`users` (
  `user_id` INT(11) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `gender` ENUM('m', 'f') NOT NULL,
  `bio` TEXT NULL,
  `latitude` DOUBLE NOT NULL,
  `longtitude` DOUBLE NOT NULL,
  `profile_picture` VARCHAR(50) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minder`.`connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minder`.`connections` (
  `connection_id` INT(11) NOT NULL,
  `from_user_id` INT(11) NOT NULL,
  `to_user_id` INT(11) NOT NULL,
  `accepted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`connection_id`),

  CONSTRAINT `from_user_id-users`
    FOREIGN KEY (`from_user_id`)
    REFERENCES `minder`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `to_user_id-users`
    FOREIGN KEY (`to_user_id`)
    REFERENCES `minder`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minder`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minder`.`likes` (
  `liked_by_user_id` INT(11) NOT NULL,
  `liked_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`liked_by_user_id`, `liked_user_id`),

  CONSTRAINT `liked_by_user_id	-users`
    FOREIGN KEY (`liked_by_user_id`)
    REFERENCES `minder`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `liked_user_id-users`
    FOREIGN KEY (`liked_user_id`)
    REFERENCES `minder`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minder`.`characteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minder`.`characteristics` (
  `characteristic_id` INT(11) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `characteristicscol` VARCHAR(45) NULL,
  PRIMARY KEY (`characteristic_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minder`.`characteristics_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minder`.`characteristics_users` (
  `characteristic_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`characteristic_id`, `user_id`),

  CONSTRAINT `characteristic_id-characteristics`
    FOREIGN KEY (`characteristic_id`)
    REFERENCES `minder`.`characteristics` (`characteristic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id-users`
    FOREIGN KEY (`user_id`)
    REFERENCES `minder`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
